List<Map<String, String>> data = [
  {
    'testName': 'Tổng phân tích tế bào máu',
    'testNameIsBold': 'true',
    'result': '4.62',
    'unit': 'T/l',
    'csbt': '3.5 - 5.5',
    'valid': 'UPL',
    'previousResult': '4.80',
    'sdResult': '220224-108713',
    'user': 'trangtq',
    'csbtValue': '35 - 55'
  },
  {
    'testName': 'RBC (Số lượng hồng cầu)',
    'testNameIsBold': 'true',
    'result': '136',
    'unit': 'g/l',
    'csbt': '3.5 - 5.5',
    'valid': 'UPL',
    'previousResult': '136',
    'sdResult': '220224-108713',
    'user': 'trangtq',
    'csbtValue': '35 - 55'
  },
  {
    'testName': 'Tổng phân tích tế bào máu',
    'testNameIsBold': 'false',
    'result': '40.6',
    'unit': '%',
    'csbt': '3.5 - 5.5',
    'valid': 'UPL',
    'previousResult': '136',
    'sdResult': '220224-108713',
    'user': 'trangtq',
    'csbtValue': '35 - 55'
  },
  // {
  //   'testName': 'HCT (Dung tích hồng cầu)',
  //   'testNameIsBold': 'false',
  //   'result': '88.0',
  //   'unit': 'fl',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'MCV (Thể tích TBHC)',
  //   'testNameIsBold': 'false',
  //   'result': '29.4',
  //   'unit': 'pg',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'MCH (Lượng Hb 1. bình HC)',
  //   'testNameIsBold': 'false',
  //   'result': '334',
  //   'unit': 'g/l',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'MCHC (nồng độ Hb TBHC)',
  //   'testNameIsBold': 'false',
  //   'result': '',
  //   'unit': 'g/l',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'CHCM (nồng độ Hb TBHC do TT)',
  //   'testNameIsBold': 'false',
  //   'result': '',
  //   'unit': '%',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'RDW (độ phân bổ HC)',
  //   'testNameIsBold': 'false',
  //   'result': '15.1',
  //   'unit': '%',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'RDW-CV (độ phân bổ HC)',
  //   'testNameIsBold': 'false',
  //   'result': '',
  //   'unit': 'g/l',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'CH (lượng Hb TBHC đo TT)',
  //   'testNameIsBold': 'false',
  //   'result': '0.05',
  //   'unit': '%',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'RDW-SD (Độ phân bổ HC)',
  //   'testNameIsBold': 'false',
  //   'result': '0.0004',
  //   'unit': 'g/l',
  //   'csbt': '3.5 - 5.5',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'HDW (độ phân bổ Hb)',
  //   'testNameIsBold': 'false',
  //   'result': '7.2',
  //   'unit': 'g/l',
  //   'csbt': '',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'NRBC% (% HC nhân)',
  //   'testNameIsBold': 'false',
  //   'result': '22.43',
  //   'unit': '%',
  //   'csbt': '',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'WBC (Số lượng bạch cầu)',
  //   'testNameIsBold': 'true',
  //   'result': '5.64',
  //   'unit': '%',
  //   'csbt': '',
  //   'valid': 'VAL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  // {
  //   'testName': 'MONO% (BC mono)',
  //   'testNameIsBold': 'false',
  //   'result': '22.43',
  //   'unit': '%',
  //   'csbt': '',
  //   'valid': 'UPL',
  //   'previousResult': '136',
  //   'sdResult': '220224-108713',
  //   'user': 'trangtq',
  //   'csbtValue': '35 - 55'
  // },
  {
    'testName': 'MONO% (BC mono)',
    'testNameIsBold': 'false',
    'result': '',
    'unit': '',
    'csbt': '',
    'valid': '',
    'previousResult': '',
    'sdResult': '',
    'user': '',
    'csbtValue': ''
  },
  // {
  //   'testName': 'EO% (% BC Lympho)',
  //   'testNameIsBold': 'false',
  //   'result': '',
  //   'unit': '',
  //   'csbt': '',
  //   'valid': '',
  //   'previousResult': '',
  //   'sdResult': '',
  //   'user': '',
  //   'csbtValue': ''
  // },
  // {
  //   'testName': 'BASO% (% BC ua baso)',
  //   'testNameIsBold': 'false',
  //   'result': '',
  //   'unit': '',
  //   'csbt': '',
  //   'valid': '',
  //   'previousResult': '',
  //   'sdResult': '',
  //   'user': '',
  //   'csbtValue': ''
  // },
];
